version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "30888:8080"  # Port host:container, aman dari konflik
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:

