version: '3.8'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta  # Ganti sesuai zona waktu lokal jika perlu
    volumes:
      - /home/hades/homelabs/sonarr/config:/config
      - /home/hades/homelabs/plex/movies:/data/movies
      - /home/hades/homelabs/plex/movies:/data/anime
      - /home/hades/homelabs/plex/movies:/data/tvseries
      - /home/hades/homelabs/plex/downloads:/downloads # tambahkan kalau kamu punya folder download
    ports:
      - 8989:8989
    restart: unless-stopped

