version: "3.8"

services:
  downtify:
    container_name: downtify
    image: henriquesebastiao/downtify:latest
    ports:
      - "30321:30321"
    volumes:
      - /home/hades/homelabs/mediacenter/media/music:/downloads
    environment:
      - CLIENT_ID=5f573c9620494bae87890c0f08a60293  # Optional
      - CLIENT_SECRET=212476d9b0f3472eaa762d90b19b0ba8  # Optional
      - DOWNTIFY_PORT=30321
    restart: unless-stopped

