version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8282:80"  # Ganti sesuai kebutuhan
    volumes:
      # - ~/homelabs/filebrowser/data:/srv
      - ~/:/srv
      - ~/homelabs/docker-labs/filebrowser/database:/database
      - ~/homelabs/docker-labs/filebrowser/config:/config
    restart: unless-stopped

