version: "3.8"

services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - /home/hades/homelabs/swingmusic:/config
      - /home/hades/homelabs/mediacenter/media/music:/music:ro
    ports:
      - "1970:1970"
    restart: unless-stopped

