version: "3.8"

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h         # Scan ulang musik setiap 1 jam
      ND_LOGLEVEL: info           # Level log normal
      ND_BASEURL: ""              # Kosongkan jika tidak di-reverse proxy
    volumes:
      - /home/hades/homelabs/navidrome/data:/data
      - /home/hades/homelabs/mediacenter/media/music:/music:ro
    restart: unless-stopped

