version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "hades@hades.com" # Ganti dengan email login kamu
      PGADMIN_DEFAULT_PASSWORD: "arema123"   # Ganti dengan password yang kuat
    ports:
      - "5050:80" # Akses pgAdmin dari browser di http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
