version: "3.8"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - NZBGET_USER=hades # optional
      - NZBGET_PASS=arema123 # optional
    volumes:
      - ./config:/config
      - /home/hades/homelabs/mediacenter/media/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

