version: '3.8'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - JELLYFIN_PublishedServerUrl=http://192.168.31.28:8096
    volumes:
      - /home/hades/homelabs/jellyfin:/config
      - /home/hades/homelabs/mediacenter/media/movies:/data/movies
      - /home/hades/homelabs/mediacenter/media/anime:/data/anime
      - /home/hades/homelabs/mediacenter/media/tvseries:/data/tvseries
      - /home/hades/homelabs/mediacenter/media/music:/music:ro
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

