version: "3.8"

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8443:8443"        # Panel HTTPS
      - "8123:8123"        # Dynmap (opsional)
      - "19132:19132/udp"  # Bedrock server
      - "25500-25600:25500-25600"  # Range untuk server Minecraft
    volumes:
      - ./docker/backups:/crafty/backups
      - ./docker/logs:/crafty/logs
      - ./docker/servers:/crafty/servers
      - ./docker/config:/crafty/app/config
      - ./docker/import:/crafty/import

